version: "3.9"
services:
  ore-miner:
    container_name: ore-miner
    build:
      context: .
    image: ore-miner
    restart: always
    command: "ore --rpc $${SOL_RPC} --keypair /app/wallet.json --priority-fee $${PRIORITY_FEE} mine --cores $${THREAD_COUNT}"
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
    env_file:
      - .env
